### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by hmacdope** [choderalab/mtenn#45]
Overall test coverage needs to go up a bit (reported at 6% currently, unsure if accurate) for this project to be considered more stable. 
This will help avoid regressions etc.

**Comment by kaminow** [comment]
:see_no_evil: yep this is definitely needed. I'll start grinding those unit tests

**Comment by kaminow** [comment]
turns out the CodeCov badge on the `main` branch was actually pointing to the CodeCov for the (very old) `master` branch, so we've actually been at ~71% which isn't too bad. this is now fixed in the #47. still working on tests but currently up to [84%](https://app.codecov.io/gh/choderalab/mtenn/tree/add-tests) :muscle:
